name: CI

on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - converted_to_draft
      - ready_for_review
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
      sha:
  repository_dispatch:
    types:
      - test-ci-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get latest and previous tag
        id: tags
        uses: JinoArch/get-latest-tag@latest

      - name: Show latest tag
        run: echo ${{ steps.tags.outputs.latestTag }}

      - name: Show previous tag
        run: echo ${{ steps.tags.outputs.previousTag }}

      - name: Show environment
        run: set

      - name: Show github context
        run: |
          jq -C . << 'END'
          ${{ toJson(github) }}
          END

      - name: Show packages
        run: dpkg -l
