name: CI

on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - converted_to_draft
      - ready_for_review
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
      sha:
  repository_dispatch:
    types:
      - test-ci-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

      - name: Show context
        run: |
          jq . << 'END'
          ${{ toJson(github) }}
          END
