name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
      sha:
  repository_dispatch:
    types:
      - test-ci-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Failure
        run: test -f foobarbaz

      - name: Setup asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            python 3.10.1
            
      - name: Show python
        run: python --version

      - name: Show environment
        run: set

      - name: Show event
        run: |
          jq . << 'END'
          ${{ toJson(github.event) }}
          END
  
