name: CI

on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - converted_to_draft
      - ready_for_review
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: environment
  repository_dispatch:
    types:
      - test-ci-dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v5

      - name: Show environment
        run: set

      - name: Show github context
        run: |
          jq -C . << 'END'
          ${{ toJson(github) }}
          END

      - name: Show secrets context
        run: |
          jq -C . << 'END'
          ${{ toJson(secrets) }}
          END

      - name: Show env context
        run: |
          jq -C . << 'END'
          ${{ toJson(env) }}
          END

      - name: Show vars context
        run: |
          jq -C . << 'END'
          ${{ toJson(vars) }}
          END

      - run: |
          echo /usr/share/dotnet/sdk/*/* | xargs -n1 | xargs -n1 -P8 rm -rf

      - run: |
          du -h -s /usr/local/lib/android/sdk/ndk/*/* | xargs -n1 | xargs -n1 -P8 rm -rf
