name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get previous release
        id: previous-release
        run: tag=$(gh release list -L 1 | cut -f3) >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          compareLink: true
          filterByMilestone: false
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          sinceTag: ${{ steps.previous-release.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          stripGeneratorNotice: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
