name: Trunk Check

## In Git repository with submodules
## run trunk.io linter
## then commit all changes
## and push to the same branch
## or create PR for main branch and automerge it

on:
  - push
  - workflow_dispatch

jobs:
  trunk:
    name: Trunk Check
    if: github.actor != 'caspiandb-build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: Use private repositories
        run: |
          cat << END > ~/.netrc
          machine github.com
            login buildbot
            password ${{ secrets.GITHUB_TOKEN }}
          END

      - name: Trunk Check
        id: trunk
        uses: trunk-io/trunk-action@v1
        continue-on-error: true
        with:
          arguments: --github-annotate-new-only=false
          check-mode: ${{ (github.event.action == 'workflow_dispatch' && 'all') || '' }}

      - name: Trunk fix
        if: steps.trunk.outcome == 'failure'
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --github-annotate=false --fix
          cache: false
          check-mode: ${{ (github.event.action == 'workflow_dispatch' && 'all') || '' }}

      - name: Commit and push to branch
        if: steps.trunk.outcome == 'failure' && github.ref != 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_email: buildbot@caspiandb.com
          author_name: caspiandb-build
          committer_email: buildbot@caspiandb.com
          committer_name: caspiandb-build
          message: Trunk fix
          pull: --rebase --autostash

      - name: Create Pull Request to main
        if: steps.trunk.outcome == 'failure' && github.ref == 'refs/heads/main'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .
          commit-message: Trunk fix
          committer: buildbot <piotr.roszatycki@gmail.com>
          author: buildbot <piotr.roszatycki@gmail.com>
          branch: trunk-fix
          delete-branch: true
          title: Trunk fix
          body: Automated changes

      - name: Enable Pull Request Automerge
        if: steps.trunk.outcome == 'failure' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
